linters:
  disable:
    - errcheck      # Temporarily disable checking for unchecked errors
    - unused        # Temporarily disable checking for unused code
    - gosimple      # Temporarily disable code simplification suggestions
    - ineffassign   # Temporarily disable checking for ineffectual assignments
    - staticcheck   # Temporarily disable static analysis checks
    - depguard      # Temporarily disable dependency restrictions

issues:
  exclude-rules:
    - path: ".*"
      linters:
        - errcheck
        - unused
        - gosimple
        - ineffassign
        - staticcheck
        - depguard

run:
  timeout: 5m
  go: "1.23" 