linters:
  disable:
    - errcheck      # Disable checking for unchecked errors
    - unused        # Disable checking for unused code
    - gosimple      # Disable code simplification suggestions
    - ineffassign   # Disable checking for ineffectual assignments
    - staticcheck   # Disable static analysis checks

issues:
  exclude-rules:
    - path: ".*"
      linters:
        - errcheck
        - unused
        - gosimple
        - ineffassign
        - staticcheck

run:
  timeout: 5m 