version: "3.8"

services:
  api:
    image: nginx:latest
    container_name: api
    labels:
      chadburn.enabled: "true"  # This line is already correct
    depends_on:
      - scheduler
    
  scheduler:
    build: .
    container_name: scheduler
    restart: unless-stopped
    command: daemon --config=/etc/chadburn.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "./test.conf:/etc/chadburn.conf"
