global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chadburn'
    static_configs:
      - targets: ['scheduler:8080']  # Using the scheduler service name from our docker-compose 