{
 "title": "Chadburn Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "chadburn_scheduler_jobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Job Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(chadburn_run_total) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(chadburn_run_errors_total) by (job_name)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(chadburn_run_duration_seconds_bucket[5m])) by (job_name, le))",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}