name: Deploy Documentation to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs-svelte/**'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd docs-svelte && bun install

      - name: Install Cloudflare adapter
        run: cd docs-svelte && bun add -d @sveltejs/adapter-cloudflare

      - name: Build site
        run: cd docs-svelte && bun run build

      - name: List output directories
        run: find docs-svelte/.svelte-kit -type d | sort

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: chadburn-docs
          directory: docs-svelte/.svelte-kit/output/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} 