name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Prepare Docker Image Tags
      - name: Prepare Docker Image
        id: prep
        run: |
          DOCKER_IMAGE=premoweb/${GITHUB_REPOSITORY#*/}
          SHORTREF=${GITHUB_SHA::8}
          BRANCH_NAME=${GITHUB_REF#refs/heads/} # Extract branch name
          
          # Replace slashes with hyphens for Docker tag compatibility
          SAFE_BRANCH_NAME=$(echo "${BRANCH_NAME}" | sed 's/\//-/g')

          # Add tags for Docker Hub Container registry
          TAGS="${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${SAFE_BRANCH_NAME}"

          # Add tags for Github Container Registry
          DOCKER_IMAGE=ghcr.io/premoweb/${GITHUB_REPOSITORY#*/}
          TAGS="${TAGS},${DOCKER_IMAGE}:${SHORTREF},${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${SAFE_BRANCH_NAME}"

          # Set output parameters.
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT

      # Step 3: Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Step 4: Set up Docker Buildx for multi-arch builds
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 6: Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Build and Push Docker Images
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ steps.prep.outputs.tags }} 